
# COMM_GET_VALUES
COMM_GET_VALUES = [
    ('temp_fet', 'h', 10),
    ('temp_motor', 'h', 10),
    ('avg_motor_current', 'i', 100),
    ('avg_input_current', 'i', 100),
    ('avg_id', 'i', 100),
    ('avg_iq', 'i', 100),
    ('duty_cycle_now', 'h', 1000),
    ('rpm', 'i', 1),
    ('v_in', 'h', 10),
    ('amp_hours', 'i', 10000),
    ('amp_hours_charged', 'i', 10000),
    ('watt_hours', 'i', 10000),
    ('watt_hours_charged', 'i', 10000),
    ('tachometer', 'i', 1),
    ('tachometer_abs', 'i', 1),
    ('mc_fault_code', 'c', 0),
    ('pid_pos_now', 'i', 1000000),
    ('app_controller_id', 'c', 0),
    ('time_ms', 'i', 1),
]

#VedderCmd.COMM_GET_VALUES_SETUP - ok
COMM_GET_VALUES_SETUP = [
    # ('dummy', 'I', 0),
    ('temp_mos', 'h', 10),
    ('temp_motor', 'h', 10),
    ('current_moto', 'i', 100),
    ('current_in', 'i', 100),
    ('duty_now', 'h', 1000),
    ('rpm', 'i', 1),
    ('speed', 'i', 1000),
    ('v_in', 'h', 10),
    ('bat_lev', '>h', 1000),
    ('amp_hours', 'i', 10000),
    ('amp_hours_charged', 'i', 10000),
    ('watt_hours', 'i', 10000),
    ('watt_hours_charged', 'i', 10000),
    ('tachometer', 'i', 1000),
    ('tachometer_abs', 'i', 1000),
    ('position', 'i', 1000000),
    ('fault_code', 'c', 0),
    ('vesc_id', 'c', 0),
    ('num_vescs', 'c', 0),
    ('battery_wh', 'i', 1000),
    ('odometer', 'i', 0),
    ('uptime', 'i', 0),
]
